HrHarmony/Controllers/SalaryController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using HrHarmony.Data.Repositories.Dto;
using HrHarmony.Consts;
using Microsoft.EntityFrameworkCore;
using HrHarmony.Data.Models.Shared;
using HrHarmony.Data.Models.ViewModels;
using HrHarmony.Data.Models.Entities.Main;
using HrHarmony.Data.Models.Interfaces.SelectOptions;
using HrHarmony.Data.Models.ViewModels.Salary;
using HrHarmony.Data.Models.Dto.Create.Main;
using HrHarmony.Data.Models.Dto.Details.Main;
using HrHarmony.Data.Models.Dto.Update.Main;

namespace HrHarmony.Controllers;

public class SalaryController : Controller
{
    private readonly IRepository<Salary, int, SalaryDto, SalaryUpdateDto, SalaryCreateDto> _salaryRepository;
    private readonly IMapper _mapper;

    public SalaryController(
        IRepository<Salary, int, SalaryDto, SalaryUpdateDto, SalaryCreateDto> salaryRepository,
        IMapper mapper
    )
    {
        _salaryRepository = salaryRepository;
        _mapper = mapper;
    }

    public async Task<IActionResult> Index(PaginationRequest paginationRequest)
    {
        var pagedEntities = await _salaryRepository.GetPagedEntitiesAsCustomObjectAsync<IndexViewModel>(paginationRequest);
        return View(_mapper.Map<PagedRecordsViewModel<IndexViewModel>>(pagedEntities));
    }

    public async Task<IActionResult> Details(int id)
    {
        return View(await _salaryRepository.GetByIdWithRelatedAsCustomObjectAsync<DetailsViewModel>(id));
    }

    public async Task<IActionResult> Create()
    {
        var createViewModel = new CreateViewModel();
        await LoadSelectOptions(createViewModel);

        return View(createViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(SalaryCreateDto entity)
    {
        if (ModelState.IsValid)
        {
            await _salaryRepository.CreateAsync(entity);

            return RedirectToAction("Index");
        }

        var createViewModel = _mapper.Map<CreateViewModel>(entity);
        await LoadSelectOptions(createViewModel);

        return View(createViewModel);
    }

    public async Task<IActionResult> Edit(int id)
    {
        return View(await _salaryRepository.GetByIdAsCustomObjectAsync<UpdateViewModel>(id));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(SalaryUpdateDto entity)
    {
        if (ModelState.IsValid)
        {
            await _salaryRepository.UpdateAsync(entity);
            return RedirectToAction("Index");
        }

        var updateViewModel = _mapper.Map<UpdateViewModel>(entity);

        return View(updateViewModel);
    }

    public async Task<IActionResult> Delete(int id)
    {
        return View(await _salaryRepository.GetByIdAsCustomObjectAsync<DeleteViewModel>(id));
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        await _salaryRepository.DeleteAsync(id);

        return RedirectToAction("Index");
    }

    public async Task<IActionResult> SearchRelatedRecords(string searchTerm, string entityName) =>
        entityName switch
        {
            EntitiesNames.Employee => Json(await _salaryRepository.GetQuery<Employee, Employee>(q => q.Where(e =>
                        e.FullName.ToLower().Contains(searchTerm.ToLower()))).Select(e =>
                        new SelectListItem { Value = e.Id.ToString(), Text = e.FullName }).OrderBy(x => x.Text).ToListAsync()),

            _ => throw new InvalidOperationException($"Unsupported entity: '{entityName}'."),
        };

    private async Task LoadSelectOptions(ILoadEmployeeOptions entity)
    {
        var query = _salaryRepository.GetQuery<Employee, Employee>(q => q.Take(100))
            .Select(e => new CustomEntity<SelectListItem> { EntityName = EntitiesNames.Employee, Item = new SelectListItem { Value = e.Id.ToString(), Text = e.FullName } });

        // jeśli walidacja nie przeszła lub jest edycja to potrzebujemy wartości tekstowej dla pola wyszukiwania połączonych rekordów
        if (entity.EmployeeId != 0)
        {
            var selectedEmployeeQ = _salaryRepository.GetQuery<Employee, Employee>(q => q.Where(e => e.Id == entity.EmployeeId))
                .Select(e => new CustomEntity<SelectListItem> { EntityName = "EmployeeText", Item = new SelectListItem { Value = e.Id.ToString(), Text = e.FullName } });

            query = query.Concat(selectedEmployeeQ);
        }

        var results = await query.OrderBy(x => x.Item.Text).ToListAsync();

        entity.EmployeeText = results.Where(c => c.EntityName == "EmployeeText").SingleOrDefault()?.Item.Text;
        entity.Employees = results.Where(c => c.EntityName == EntitiesNames.Employee).Select(e => e.Item);
    }
}

HrHarmony/Views/Salary/Create.cshtml
@using HrHarmony.Data.Models.ViewModels.Salary;
@using HrHarmony.Helpers;
@model CreateViewModel

@{
    ViewData["Title"] = "Utwórz wynagrodzenie";
    var controllerName = ViewContext.RouteData.Values["controller"].ToString();
}

<h2>Utwórz wynagrodzenie</h2>

@using (Html.BeginForm("Create", "Salary", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(model => model.PaymentDate)
        @Html.TextBoxFor(model => model.PaymentDate, new { @class = "form-control", @type = "datetime-local" })
        @Html.ValidationMessageFor(model => model.PaymentDate, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmployeeId)
        @Html.RecordsSearchComboBoxFor(nameof(Model.EmployeeId), Model.EmployeeId, Model.EmployeeText, Model.Employees, "Wyszukaj pracownika", controllerName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BasicSalary)
        @Html.TextBoxFor(model => model.BasicSalary, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.BasicSalary, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AdditionalSalary)
        @Html.TextBoxFor(model => model.AdditionalSalary, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.AdditionalSalary, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Bonuses)
        @Html.TextBoxFor(model => model.Bonuses, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Bonuses, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Allowances)
        @Html.TextBoxFor(model => model.Allowances, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Allowances, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ZUSContributions)
        @Html.TextBoxFor(model => model.ZUSContributions, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ZUSContributions, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IncomeTax)
        @Html.TextBoxFor(model => model.IncomeTax, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IncomeTax, "", new { @class = "text-danger" })
    </div>

    @await Html.PartialAsync("~/Views/Shared/Records/_FormButtons.cshtml")
}

@section Scripts {
    <script src="~/js/searchRelatedRecords.js"></script>
}

HrHarmony/Views/Salary/Delete.cshtml
@using HrHarmony.Data.Models.ViewModels.Salary;
@model DeleteViewModel

@{
    ViewData["Title"] = "Usuń wynagrodzenie";
}

<h2>Usunąć wynagrodzenie z @Model.PaymentDate?</h2>

<form asp-controller="Salary" asp-action="Delete" method="post">
    @Html.AntiForgeryToken()
    <input type="hidden" asp-for="Id" value="@Model.Id" />
    @await Html.PartialAsync("~/Views/Shared/Records/_DeleteFormButtons.cshtml")
</form>

HrHarmony/Views/Salary/Details.cshtml
@using HrHarmony.Data.Models.ViewModels.Salary;
@model DetailsViewModel

@{
    ViewData["Title"] = "Szczegóły wynagrodzenia";
}

@if (Layout != null)
{
    <h2 class="text-center">Szczegóły wynagrodzenia</h2>

    @:<div class="table-responsive">
        @:<table class="table table-bordered table-hover">
            @:<thead class="table-dark">
                @await Html.PartialAsync("~/Views/Salary/_Columns.cshtml")
            @:</thead>
            @:<tbody>
}

<tr>
    <td>@Model.PaymentDate</td>
    <td>@Model.Employee?.FullName</td>
    <td>@Model.BasicSalary</td>
    <td>@Model.AdditionalSalary</td>
    <td>@Model.Bonuses</td>
    <td>@Model.Allowances</td>
    <td>@Model.ZUSContributions</td>
    <td>@Model.IncomeTax</td>

    <td class="d-flex">
        <a class="btn btn-info btn-sm ms-2" asp-controller="Salary" asp-action="Edit" asp-route-id="@Model.Id">Edytuj</a>
        <a class="btn btn-danger btn-sm ms-2" asp-controller="Salary" asp-action="Delete" asp-route-id="@Model.Id">Usuń</a>
    </td>
</tr>

@if (Layout != null)
{
            @:</tbody>
        @:</table>
    @:</div>

    @await Html.PartialAsync("~/Views/Shared/Records/_ComeBackButton.cshtml")
}

HrHarmony/Views/Salary/Edit.cshtml
@using HrHarmony.Data.Models.ViewModels.Salary;
@model UpdateViewModel

@{
    ViewData["Title"] = "Edycja wynagrodzenia";
}

<h2>Edytuj wynagrodzenie</h2>

@using (Html.BeginForm("Edit", "Salary", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(model => model.BasicSalary)
        @Html.TextBoxFor(model => model.BasicSalary, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.BasicSalary, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AdditionalSalary)
        @Html.TextBoxFor(model => model.AdditionalSalary, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.AdditionalSalary, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Bonuses)
        @Html.TextBoxFor(model => model.Bonuses, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Bonuses, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Allowances)
        @Html.TextBoxFor(model => model.Allowances, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.Allowances, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ZUSContributions)
        @Html.TextBoxFor(model => model.ZUSContributions, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ZUSContributions, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.IncomeTax)
        @Html.TextBoxFor(model => model.IncomeTax, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.IncomeTax, "", new { @class = "text-danger" })
    </div>

    @await Html.PartialAsync("~/Views/Shared/Records/_FormButtons.cshtml")
}

@section Scripts {
    <script src="~/js/searchRelatedRecords.js"></script>
}

HrHarmony/Views/Salary/Index.cshtml
@using HrHarmony.Data.Models.ViewModels.Salary;
@using HrHarmony.Data.Models.ViewModels;
@model PagedRecordsViewModel<IndexViewModel>

@{
    ViewData["Title"] = "Wynagrodzenia";
}

@await Html.PartialAsync("~/Views/Shared/Records/_RecordsListHeader.cshtml", "wynagrodzeń")
@await Html.PartialAsync("~/Views/Shared/Records/_RecordsList.cshtml")

HrHarmony/Views/Salary/_Columns.cshtml
<tr>
    <th>Data płatności</th>
    <th>Pracownik</th>
    <th>Wynagrodzenie podstawowe</th>
    <th>Dodatkowe wynagrodzenie</th>
    <th>Bonusy</th>
    <th>Dodatki</th>
    <th>Składki ZUS</th>
    <th>Podatek dochodowy</th>
    <th>Akcje</th>
</tr>