HrHarmony/Controllers/AbsenceController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using HrHarmony.Data.Repositories.Dto;
using HrHarmony.Consts;
using Microsoft.EntityFrameworkCore;
using HrHarmony.Data.Models.Interfaces;
using HrHarmony.Data.Models.Shared;
using HrHarmony.Data.Models.ViewModels;
using HrHarmony.Data.Models.Entities.Dictionary;
using HrHarmony.Data.Models.Entities.Main;
using HrHarmony.Data.Models.ViewModels.Absence;
using HrHarmony.Data.Models.Dto.Create.Main;
using HrHarmony.Data.Models.Dto.Details.Main;
using HrHarmony.Data.Models.Dto.Update.Main;

namespace HrHarmony.Controllers;

public class AbsenceController : Controller
{
    private readonly IRepository<Absence, int, AbsenceDto, AbsenceUpdateDto, AbsenceCreateDto> _absenceRepository;
    private readonly IMapper _mapper;

    public AbsenceController(
        IRepository<Absence, int, AbsenceDto, AbsenceUpdateDto, AbsenceCreateDto> absenceRepository,
        IMapper mapper
    )
    {
        _absenceRepository = absenceRepository;
        _mapper = mapper;
    }

    public async Task<IActionResult> Index(PaginationRequest paginationRequest)
    {
        var pagedEntities = await _absenceRepository.GetPagedEntitiesAsCustomObjectAsync<IndexViewModel>(paginationRequest);
        return View(_mapper.Map<PagedRecordsViewModel<IndexViewModel>>(pagedEntities));
    }

    public async Task<IActionResult> Details(int id)
    {
        return View(await _absenceRepository.GetByIdWithRelatedAsCustomObjectAsync<DetailsViewModel>(id));
    }

    public async Task<IActionResult> Create()
    {
        var createViewModel = new CreateViewModel();
        await LoadSelectOptions(createViewModel);

        return View(createViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(AbsenceCreateDto entity)
    {
        if (ModelState.IsValid)
        {
            await _absenceRepository.CreateAsync(entity);

            return RedirectToAction("Index");
        }

        var createViewModel = _mapper.Map<CreateViewModel>(entity);
        await LoadSelectOptions(createViewModel);

        return View(createViewModel);
    }

    public async Task<IActionResult> Edit(int id)
    {
        var updateViewModel = await _absenceRepository.GetByIdAsCustomObjectAsync<UpdateViewModel>(id);
        await LoadSelectOptions(updateViewModel);

        return View(updateViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(AbsenceUpdateDto entity)
    {
        if (ModelState.IsValid)
        {
            await _absenceRepository.UpdateAsync(entity);
            return RedirectToAction("Index");
        }

        var updateViewModel = _mapper.Map<UpdateViewModel>(entity);
        await LoadSelectOptions(updateViewModel);

        return View(updateViewModel);
    }

    public async Task<IActionResult> Delete(int id)
    {
        return View(await _absenceRepository.GetByIdAsCustomObjectAsync<DeleteViewModel>(id));
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        await _absenceRepository.DeleteAsync(id);

        return RedirectToAction("Index");
    }

    /// TODO: Zrobić paginacje. Na końcu listy strzałka do kliknięcia żeby pobrała się kolejna strona?
    public async Task<IActionResult> SearchRelatedRecords(string searchTerm, string entityName) =>
        entityName switch 
        {
            EntitiesNames.Employee => Json(await _absenceRepository.GetQuery<Employee, Employee>(q => q.Where(e =>
                        e.FullName.ToLower().Contains(searchTerm.ToLower()))).Select(e =>
                        new SelectListItem { Value = e.Id.ToString(), Text = e.FullName }).OrderBy(x => x.Text).ToListAsync()),
            
            _ => throw new InvalidOperationException($"Unsupported entity: '{entityName}'."),
        };
    
    private async Task LoadSelectOptions(ILoadGroupedAbsenceOptions entity)
    {
        var absenceTypesQ = _absenceRepository.GetQuery<AbsenceType, CustomEntity<SelectListItem>>(q =>
            q.Select(e => new CustomEntity<SelectListItem> { EntityName = EntitiesNames.AbsenceType, Item = new SelectListItem { Value = e.Id.ToString(), Text = e.TypeName } }));

        var employeesQ = _absenceRepository.GetQuery<Employee, Employee>(q => q.Take(100))
            .Select(e => new CustomEntity<SelectListItem> { EntityName = EntitiesNames.Employee, Item = new SelectListItem { Value = e.Id.ToString(), Text = e.FullName } });

        // jeśli walidacja nie przeszła lub jest edycja to potrzebujemy wartości tekstowej dla pola wyszukiwania połączonych rekordów
        var query = absenceTypesQ.Concat(employeesQ);
        if (entity.EmployeeId != 0)
        {
            var selectedEmployeeQ = _absenceRepository.GetQuery<Employee, Employee>(q => q.Where(e => e.Id == entity.EmployeeId))
                .Select(e => new CustomEntity<SelectListItem> { EntityName = "EmployeeText", Item = new SelectListItem { Value = e.Id.ToString(), Text = e.FullName } });

            query = query.Concat(selectedEmployeeQ);
        }

        var results = await query.OrderBy(x => x.Item.Text).ToListAsync();

        entity.EmployeeText = results.Where(c => c.EntityName == "EmployeeText").SingleOrDefault()?.Item.Text;
        entity.AbsenceTypes = results.Where(c => c.EntityName == EntitiesNames.AbsenceType).Select(e => e.Item);
        entity.Employees = results.Where(c => c.EntityName == EntitiesNames.Employee).Select(e => e.Item);
    }
}

HrHarmony/Views/Absence/Create.cshtml
@using HrHarmony.Data.Models.ViewModels.Absence;
@using HrHarmony.Helpers;
@model CreateViewModel

@{
    ViewData["Title"] = "Utwórz absencje";
    var controllerName = ViewContext.RouteData.Values["controller"].ToString();
}

<h2>Utwórz absencje</h2>

@using (Html.BeginForm("Create", "Absence", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(model => model.StartDate)
        @Html.TextBoxFor(model => model.StartDate, new { @class = "form-control", @type = "datetime-local" })
        @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate)
        @Html.TextBoxFor(model => model.EndDate, new { @class = "form-control", @type = "datetime-local" })
        @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.AbsenceTypeId)
        @Html.DropDownListFor(model => model.AbsenceTypeId, Model.AbsenceTypes, "Wybierz rodzaj absencji", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.AbsenceTypeId, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmployeeId)
        @Html.RecordsSearchComboBoxFor(nameof(Model.EmployeeId), Model.EmployeeId, Model.EmployeeText, Model.Employees, "Wyszukaj pracownika", controllerName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
    </div>

    @await Html.PartialAsync("~/Views/Shared/Records/_FormButtons.cshtml")
}

@section Scripts {
    <script src="~/js/searchRelatedRecords.js"></script>
}

HrHarmony/Views/Absence/Delete.cshtml
@using HrHarmony.Data.Models.ViewModels.Absence;
@model DeleteViewModel

@{
    ViewData["Title"] = "Usuń absencję";
}

<h2>Usunąć absencję z okresu: @Model.StartDate - @Model.EndDate?</h2>

<form asp-controller="Absence" asp-action="Delete" method="post">
    @Html.AntiForgeryToken()
    <input type="hidden" asp-for="Id" value="@Model.Id" />
    @await Html.PartialAsync("~/Views/Shared/Records/_DeleteFormButtons.cshtml")
</form>

HrHarmony/Views/Absence/Details.cshtml
@using HrHarmony.Data.Models.ViewModels.Absence;
@model DetailsViewModel

@{
    ViewData["Title"] = "Szczegóły absencji";
}

@if (Layout != null)
{
    <h2 class="text-center">Szczegóły absencji</h2>

    @:<div class="table-responsive">
        @:<table class="table table-bordered table-hover">
            @:<thead class="table-dark">
                @await Html.PartialAsync("~/Views/Absence/_Columns.cshtml")
            @:</thead>
            @:<tbody>
}

<tr>
    <td>@Model.StartDate</td>
    <td>@Model.EndDate</td>
    <td>@Model.AbsenceType?.TypeName</td>
    <td>@Model.Employee?.FullName</td>

    <td class="d-flex">
        <a class="btn btn-info btn-sm ms-2" asp-controller="Absence" asp-action="Edit" asp-route-id="@Model.Id">Edytuj</a>
        <a class="btn btn-danger btn-sm ms-2" asp-controller="Absence" asp-action="Delete" asp-route-id="@Model.Id">Usuń</a>
    </td>
</tr>

@if (Layout != null)
{
                @:</tbody>
        @:</table>
    @:</div>

    @await Html.PartialAsync("~/Views/Shared/Records/_ComeBackButton.cshtml")
}

HrHarmony/Views/Absence/Edit.cshtml
@using HrHarmony.Data.Models.ViewModels.Absence;
@using HrHarmony.Helpers;
@model UpdateViewModel

@{
    ViewData["Title"] = "Edycja absencji";
    var controllerName = ViewContext.RouteData.Values["controller"].ToString();
}

<h2>Edytuj absencje</h2>

@using (Html.BeginForm("Edit", "Absence", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(model => model.AbsenceTypeId)
        @Html.DropDownListFor(model => model.AbsenceTypeId, Model.AbsenceTypes, "Wybierz rodzaj absencji", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.AbsenceTypeId, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmployeeId)
        @Html.RecordsSearchComboBoxFor(nameof(Model.EmployeeId), Model.EmployeeId, Model.EmployeeText, Model.Employees, "Wyszukaj pracownika", controllerName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
    </div>

    @await Html.PartialAsync("~/Views/Shared/Records/_FormButtons.cshtml")
}

@section Scripts {
    <script src="~/js/searchRelatedRecords.js"></script>
}

HrHarmony/Views/Absence/Index.cshtml
@using HrHarmony.Data.Models.ViewModels.Absence;
@using HrHarmony.Data.Models.ViewModels;
@model PagedRecordsViewModel<IndexViewModel>

@{
    ViewData["Title"] = "Absencje";
}

@await Html.PartialAsync("~/Views/Shared/Records/_RecordsListHeader.cshtml", "absencji")
@await Html.PartialAsync("~/Views/Shared/Records/_RecordsList.cshtml")

HrHarmony/Views/Absence/_Columns.cshtml
<tr>
    <th>Data rozpoczęcia</th>
    <th>Data zakończenia</th>
    <th>Rodzaj absencji</th>
    <th>Pracownik</th>
    <th>Akcje</th>
</tr>