HrHarmony/Controllers/ExperienceController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using HrHarmony.Data.Repositories.Dto;
using HrHarmony.Data.Models.Shared;
using HrHarmony.Data.Models.ViewModels;
using HrHarmony.Data.Models.Entities.Dictionary;
using HrHarmony.Data.Models.ViewModels.Experience;
using HrHarmony.Data.Models.Dto.Create.Dictionary;
using HrHarmony.Data.Models.Dto.Details.Dictionary;
using HrHarmony.Data.Models.Dto.Update.Dictionary;

namespace HrHarmony.Controllers;

public class ExperienceController : Controller
{
    private readonly IRepository<Experience, int, ExperienceDto, ExperienceUpdateDto, ExperienceCreateDto> _experienceRepository;
    private readonly IMapper _mapper;

    public ExperienceController(
        IRepository<Experience, int, ExperienceDto, ExperienceUpdateDto, ExperienceCreateDto> experienceRepository,
        IMapper mapper
    )
    {
        _experienceRepository = experienceRepository;
        _mapper = mapper;
    }

    public async Task<IActionResult> Index(PaginationRequest paginationRequest)
    {
        var pagedEntities = await _experienceRepository.GetPagedEntitiesAsCustomObjectAsync<IndexViewModel>(paginationRequest);
        return View(_mapper.Map<PagedRecordsViewModel<IndexViewModel>>(pagedEntities));
    }

    public async Task<IActionResult> Details(int id)
    {
        return View(await _experienceRepository.GetByIdAsCustomObjectAsync<DetailsViewModel>(id));
    }

    public IActionResult Create()
    {
        var createViewModel = new CreateViewModel();

        return View(createViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(ExperienceCreateDto entity)
    {
        if (ModelState.IsValid)
        {
            await _experienceRepository.CreateAsync(entity);

            return RedirectToAction("Index");
        }

        var createViewModel = _mapper.Map<CreateViewModel>(entity);

        return View(createViewModel);
    }

    public async Task<IActionResult> Edit(int id)
    {
        return View(await _experienceRepository.GetByIdAsCustomObjectAsync<UpdateViewModel>(id));
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(ExperienceUpdateDto entity)
    {
        if (ModelState.IsValid)
        {
            await _experienceRepository.UpdateAsync(entity);
            return RedirectToAction("Index");
        }
        
        var updateViewModel = _mapper.Map<UpdateViewModel>(entity);

        return View(updateViewModel);
    }

    public async Task<IActionResult> Delete(int id)
    {
        return View(await _experienceRepository.GetByIdAsCustomObjectAsync<DeleteViewModel>(id));
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        await _experienceRepository.DeleteAsync(id);

        return RedirectToAction("Index");
    }
}

HrHarmony/Views/Experience/Create.cshtml
@using HrHarmony.Data.Models.ViewModels.Experience;
@model CreateViewModel

@{
    ViewData["Title"] = "Utwórz doświadczenie zawodowe";
}

<h2>Utwórz doświadczenie zawodowe</h2>

@using (Html.BeginForm("Create", "Experience", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(model => model.ExperienceName)
        @Html.TextBoxFor(model => model.ExperienceName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ExperienceName, "", new { @class = "text-danger" })
    </div>

    @await Html.PartialAsync("~/Views/Shared/Records/_FormButtons.cshtml")
}

HrHarmony/Views/Experience/Delete.cshtml
@using HrHarmony.Data.Models.ViewModels.Experience;
@model DeleteViewModel

@{
    ViewData["Title"] = "Usuń doświadczenie zawodowe";
}

<h2>Usunąć doświadczenie zawodowe - @Model.ExperienceName?</h2>

<form asp-controller="Experience" asp-action="Delete" method="post">
    @Html.AntiForgeryToken()
    <input type="hidden" asp-for="Id" value="@Model.Id" />
    @await Html.PartialAsync("~/Views/Shared/Records/_DeleteFormButtons.cshtml")
</form>

HrHarmony/Views/Experience/Details.cshtml
@using HrHarmony.Data.Models.ViewModels.Experience;
@model DetailsViewModel

@{
    ViewData["Title"] = "Szczegóły doświadczenia zawodowego";
}

@if (Layout != null)
{
    <h2 class="text-center">Szczegóły doświadczenia zawodowego</h2>    
}

<div class="table-responsive">
    <table class="table table-bordered table-hover">
        <thead class="table-dark">
            <tr>
                <th>Nazwa doświadczenia</th>
                <th>Akcje</th>
            </tr>
        </thead>
        <tbody>
            <tr>
                <td>@Model.ExperienceName</td>

                <td class="d-flex">
                    <a class="btn btn-info btn-sm ms-2" asp-controller="Experience" asp-action="Edit" asp-route-id="@Model.Id">Edytuj</a>
                    <a class="btn btn-danger btn-sm ms-2" asp-controller="Experience" asp-action="Delete" asp-route-id="@Model.Id">Usuń</a>
                </td>
            </tr>
        </tbody>
    </table>
</div>

@if (Layout != null)
{
    @await Html.PartialAsync("~/Views/Shared/Records/_ComeBackButton.cshtml")
}

HrHarmony/Views/Experience/Edit.cshtml
@using HrHarmony.Data.Models.ViewModels.Experience;
@model UpdateViewModel

@{
    ViewData["Title"] = "Edycja doświadczenia zawodowego";
}

<h2>Edytuj doświadczenie zawodowe</h2>

@using (Html.BeginForm("Edit", "Experience", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(model => model.ExperienceName)
        @Html.TextBoxFor(model => model.ExperienceName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ExperienceName, "", new { @class = "text-danger" })
    </div>

    @await Html.PartialAsync("~/Views/Shared/Records/_FormButtons.cshtml")
}

HrHarmony/Views/Experience/Index.cshtml
@using HrHarmony.Data.Models.ViewModels.Experience;
@using HrHarmony.Data.Models.ViewModels;
@model PagedRecordsViewModel<IndexViewModel>

@{
    ViewData["Title"] = "Doświadczenia zawodowe";
}

@await Html.PartialAsync("~/Views/Shared/Records/_RecordsListHeader.cshtml", "doświadczeń zawodowych")
@await Html.PartialAsync("~/Views/Shared/Records/_RecordsList.cshtml")