HrHarmony/Controllers/EmploymentContractController.cs
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using HrHarmony.Data.Repositories.Dto;
using HrHarmony.Consts;
using Microsoft.EntityFrameworkCore;
using HrHarmony.Data.Models.Interfaces;
using HrHarmony.Data.Models.Shared;
using HrHarmony.Data.Models.ViewModels;
using HrHarmony.Data.Models.Entities.Dictionary;
using HrHarmony.Data.Models.Entities.Main;
using HrHarmony.Data.Models.ViewModels.EmploymentContract;
using HrHarmony.Data.Models.Dto.Create.Main;
using HrHarmony.Data.Models.Dto.Details.Main;
using HrHarmony.Data.Models.Dto.Update.Main;

namespace HrHarmony.Controllers;

public class EmploymentContractController : Controller
{
    private readonly IRepository<EmploymentContract, int, EmploymentContractDto, EmploymentContractUpdateDto, EmploymentContractCreateDto> _employmentContractRepository;
    private readonly IMapper _mapper;

    public EmploymentContractController(
        IRepository<EmploymentContract, int, EmploymentContractDto, EmploymentContractUpdateDto, EmploymentContractCreateDto> employmentContractRepository,
        IMapper mapper
    )
    {
        _employmentContractRepository = employmentContractRepository;
        _mapper = mapper;
    }

    public async Task<IActionResult> Index(PaginationRequest paginationRequest)
    {
        var pagedEntities = await _employmentContractRepository.GetPagedEntitiesAsCustomObjectAsync<IndexViewModel>(paginationRequest);
        return View(_mapper.Map<PagedRecordsViewModel<IndexViewModel>>(pagedEntities));
    }

    public async Task<IActionResult> Details(int id)
    {
        return View(await _employmentContractRepository.GetByIdWithRelatedAsCustomObjectAsync<DetailsViewModel>(id));
    }

    public async Task<IActionResult> Create()
    {
        var createViewModel = new CreateViewModel();
        await LoadSelectOptions(createViewModel);

        return View(createViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Create(EmploymentContractCreateDto entity)
    {
        if (ModelState.IsValid)
        {
            await _employmentContractRepository.CreateAsync(entity);

            return RedirectToAction("Index");
        }

        var createViewModel = _mapper.Map<CreateViewModel>(entity);
        await LoadSelectOptions(createViewModel);

        return View(createViewModel);
    }

    public async Task<IActionResult> Edit(int id)
    {
        var updateViewModel = await _employmentContractRepository.GetByIdAsCustomObjectAsync<UpdateViewModel>(id);
        await LoadSelectOptions(updateViewModel);

        return View(updateViewModel);
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> Edit(EmploymentContractUpdateDto entity)
    {
        if (ModelState.IsValid)
        {
            await _employmentContractRepository.UpdateAsync(entity);
            return RedirectToAction("Index");
        }

        var updateViewModel = _mapper.Map<UpdateViewModel>(entity);
        await LoadSelectOptions(updateViewModel);

        return View(updateViewModel);
    }

    public async Task<IActionResult> Delete(int id)
    {
        return View(await _employmentContractRepository.GetByIdAsCustomObjectAsync<DeleteViewModel>(id));
    }

    [HttpPost, ActionName("Delete")]
    [ValidateAntiForgeryToken]
    public async Task<IActionResult> DeleteConfirmed(int id)
    {
        await _employmentContractRepository.DeleteAsync(id);

        return RedirectToAction("Index");
    }

    public async Task<IActionResult> SearchRelatedRecords(string searchTerm, string entityName) =>
        entityName switch
        {
            EntitiesNames.Employee => Json(await _employmentContractRepository.GetQuery<Employee, Employee>(q => q.Where(e =>
                        e.FullName.ToLower().Contains(searchTerm.ToLower()))).Select(e =>
                        new SelectListItem { Value = e.Id.ToString(), Text = e.FullName }).OrderBy(x => x.Text).ToListAsync()),

            _ => throw new InvalidOperationException($"Unsupported entity: '{entityName}'."),
        };

    private async Task LoadSelectOptions(ILoadGroupedEmploymentContractOptions entity)
    {
        var contractTypesQ = _employmentContractRepository.GetQuery<ContractType, CustomEntity<SelectListItem>>(q =>
            q.Select(e => new CustomEntity<SelectListItem> { EntityName = EntitiesNames.ContractType, Item = new SelectListItem { Value = e.Id.ToString(), Text = e.TypeName } }));

        var employeesQ = _employmentContractRepository.GetQuery<Employee, Employee>(q => q.Take(100))
            .Select(e => new CustomEntity<SelectListItem> { EntityName = EntitiesNames.Employee, Item = new SelectListItem { Value = e.Id.ToString(), Text = e.FullName } });

        // jeśli walidacja nie przeszła lub jest edycja to potrzebujemy wartości tekstowej dla pola wyszukiwania połączonych rekordów
        var query = contractTypesQ.Concat(employeesQ);
        if (entity.EmployeeId != 0)
        {
            var selectedEmployeeQ = _employmentContractRepository.GetQuery<Employee, Employee>(q => q.Where(e => e.Id == entity.EmployeeId))
                .Select(e => new CustomEntity<SelectListItem> { EntityName = "EmployeeText", Item = new SelectListItem { Value = e.Id.ToString(), Text = e.FullName } });

            query = query.Concat(selectedEmployeeQ);   
        }

        var results = await query.OrderBy(x => x.Item.Text).ToListAsync();

        entity.EmployeeText = results.Where(c => c.EntityName == "EmployeeText").SingleOrDefault()?.Item.Text;
        entity.ContractTypes = results.Where(c => c.EntityName == EntitiesNames.ContractType).Select(e => e.Item);
        entity.Employees = results.Where(c => c.EntityName == EntitiesNames.Employee).Select(e => e.Item);
    }
}

HrHarmony/Views/EmploymentContract/Create.cshtml
@using HrHarmony.Data.Models.ViewModels.EmploymentContract;
@using HrHarmony.Helpers;
@model CreateViewModel

@{
    ViewData["Title"] = "Utwórz umowę pracownika";
    var controllerName = ViewContext.RouteData.Values["controller"].ToString();
}

<h2>Utwórz umowę pracownika</h2>

@using (Html.BeginForm("Create", "EmploymentContract", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(model => model.ContractNumber)
        @Html.TextBoxFor(model => model.ContractNumber, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ContractNumber, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContractSigningDate)
        @Html.TextBoxFor(model => model.ContractSigningDate, new { @class = "form-control", @type = "date" })
        @Html.ValidationMessageFor(model => model.ContractSigningDate, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate)
        @Html.TextBoxFor(model => model.StartDate, new { @class = "form-control", @type = "date" })
        @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate)
        @Html.TextBoxFor(model => model.EndDate, new { @class = "form-control", @type = "date" })
        @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContractTypeId)
        @Html.DropDownListFor(model => model.ContractTypeId, Model.ContractTypes, "Wybierz rodzaj umowy", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ContractTypeId, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmployeeId)
        @Html.RecordsSearchComboBoxFor(nameof(Model.EmployeeId), Model.EmployeeId, Model.EmployeeText, Model.Employees, "Wyszukaj pracownika", controllerName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HourlyRate)
        @Html.TextBoxFor(model => model.HourlyRate, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.HourlyRate, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MonthlyRate)
        @Html.TextBoxFor(model => model.MonthlyRate, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.MonthlyRate, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BasicSalary)
        @Html.TextBoxFor(model => model.BasicSalary, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.BasicSalary, "", new { @class = "text-danger" })
    </div>

    @await Html.PartialAsync("~/Views/Shared/Records/_FormButtons.cshtml")
}

@section Scripts {
    <script src="~/js/searchRelatedRecords.js"></script>
}

HrHarmony/Views/EmploymentContract/Delete.cshtml
@using HrHarmony.Data.Models.ViewModels.EmploymentContract;
@model DeleteViewModel

@{
    ViewData["Title"] = "Usuń umowę pracownika";
}

<h2>Usunąć umowę pracownika o numerze @Model.ContractNumber?</h2>

<form asp-controller="EmploymentContract" asp-action="Delete" method="post">
    @Html.AntiForgeryToken()
    <input type="hidden" asp-for="Id" value="@Model.Id" />
    @await Html.PartialAsync("~/Views/Shared/Records/_DeleteFormButtons.cshtml")
</form>

HrHarmony/Views/EmploymentContract/Details.cshtml
@using HrHarmony.Data.Models.ViewModels.EmploymentContract;
@model DetailsViewModel

@{
    ViewData["Title"] = "Szczegóły umowy pracownika";
}

@if (Layout != null)
{
    <h2 class="text-center">Szczegóły umowy pracownika</h2>

    @:<div class="table-responsive">
        @:<table class="table table-bordered table-hover">
            @:<thead class="table-dark">
                @await Html.PartialAsync("~/Views/EmploymentContract/_Columns.cshtml")
            @:</thead>
            @:<tbody>
}

<tr>
    <td>@Model.ContractNumber</td>
    <td>@Model.ContractSigningDate</td>
    <td>@Model.StartDate</td>
    <td>@Model.EndDate</td>
    <td>@Model.ContractType?.TypeName</td>
    <td>@Model.Employee?.FullName</td>
    <td>@Model.HourlyRate</td>
    <td>@Model.MonthlyRate</td>
    <td>@Model.BasicSalary</td>

    <td class="d-flex">
        <a class="btn btn-info btn-sm ms-2" asp-controller="EmploymentContract" asp-action="Edit" asp-route-id="@Model.Id">Edytuj</a>
        <a class="btn btn-danger btn-sm ms-2" asp-controller="EmploymentContract" asp-action="Delete" asp-route-id="@Model.Id">Usuń</a>
    </td>
</tr>

@if (Layout != null)
{
    
            @:</tbody>
        @:</table>
    @:</div>

    @await Html.PartialAsync("~/Views/Shared/Records/_ComeBackButton.cshtml")
}

HrHarmony/Views/EmploymentContract/Edit.cshtml
@using HrHarmony.Data.Models.ViewModels.EmploymentContract;
@using HrHarmony.Helpers;
@model UpdateViewModel

@{
    ViewData["Title"] = "Edycja umowy pracownika";
    var controllerName = ViewContext.RouteData.Values["controller"].ToString();
}

<h2>Edytuj umowę pracownika</h2>

@using (Html.BeginForm("Edit", "EmploymentContract", FormMethod.Post))
{
    <div class="form-group">
        @Html.LabelFor(model => model.ContractSigningDate)
        @Html.TextBoxFor(model => model.ContractSigningDate, Model.ContractSigningDate.ToString("yyyy-MM-dd"), new { @class = "form-control", @type = "date" })
        @Html.ValidationMessageFor(model => model.ContractSigningDate, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.StartDate)
        @Html.TextBoxFor(model => model.StartDate, Model.StartDate.ToString("yyyy-MM-dd"), new { @class = "form-control", @type = "date" })
        @Html.ValidationMessageFor(model => model.StartDate, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EndDate)
        @Html.TextBoxFor(model => model.EndDate, Model.EndDate?.ToString("yyyy-MM-dd"), new { @class = "form-control", @type = "date" })
        @Html.ValidationMessageFor(model => model.EndDate, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ContractTypeId)
        @Html.DropDownListFor(model => model.ContractTypeId, Model.ContractTypes, "Wybierz rodzaj umowy", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.ContractTypeId, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.EmployeeId)
        @Html.RecordsSearchComboBoxFor(nameof(Model.EmployeeId), Model.EmployeeId, Model.EmployeeText, Model.Employees, "Wyszukaj pracownika", controllerName, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.EmployeeId, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.HourlyRate)
        @Html.TextBoxFor(model => model.HourlyRate, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.HourlyRate, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MonthlyRate)
        @Html.TextBoxFor(model => model.MonthlyRate, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.MonthlyRate, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.BasicSalary)
        @Html.TextBoxFor(model => model.BasicSalary, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.BasicSalary, "", new { @class = "text-danger" })
    </div>

    @await Html.PartialAsync("~/Views/Shared/Records/_FormButtons.cshtml")
}

@section Scripts {
    <script src="~/js/searchRelatedRecords.js"></script>
}

HrHarmony/Views/EmploymentContract/Index.cshtml
@using HrHarmony.Data.Models.ViewModels.EmploymentContract;
@using HrHarmony.Data.Models.ViewModels;
@model PagedRecordsViewModel<IndexViewModel>

@{
    ViewData["Title"] = "Umowy pracowników";
}

@await Html.PartialAsync("~/Views/Shared/Records/_RecordsListHeader.cshtml", "umów pracowników")
@await Html.PartialAsync("~/Views/Shared/Records/_RecordsList.cshtml")

HrHarmony/Views/EmploymentContract/_Columns.cshtml
<tr>
    <th>Numer umowy</th>
    <th>Data podpisania umowy</th>
    <th>Data rozpoczęcia</th>
    <th>Data końca</th>
    <th>Rodzaj umowy</th>
    <th>Pracownik</th>
    <th>Stawka godzinowa</th>
    <th>Stawka miesięczna</th>
    <th>Wynagrodzenie podstawowe</th>
    <th>Akcje</th>
</tr>